name: Build and Deploy Sphinx Docs
# TODO - only on main
on:
  push:
    branches: [ docs/docs-page ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Sphinx dependencies
        run: pip install -r docs/requirements.txt

      # required for doc generation
      - name: Install llumpy
        run: pip install -e .

      - name: Build Sphinx docs
        run: sphinx-build -b html docs docs/build/html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: documentation
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4